# Form implementation generated from reading ui file 'ADMINLOGIN.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(1095, 836)
        LoginForm.resize(1095, 836)
        LoginForm.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        LoginForm.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.loginWindow = QtWidgets.QWidget(parent=LoginForm)
        self.loginWindow.setGeometry(QtCore.QRect(100, 70, 881, 581))
        self.loginWindow.setAutoFillBackground(False)
        self.loginWindow.setStyleSheet("QPushButton#loginbtn{\n"
                                       "    background-color:rgba(85, 98, 112, 255);\n"
                                       "    color:rgba(255, 255, 255, 200);\n"
                                       "    border-radius: 10px;\n"
                                       "}\n"
                                       "QPushButton#loginbtn:pressed{\n"
                                       "    padding-left: 5px;\n"
                                       "    padding-top: 5px;\n"
                                       "    background-color:rgba(255, 107, 107, 255);\n"
                                       "    background-position: calc(100% - 10px)center;\n"
                                       "}\n"
                                       "QPushButton#loginbtn:hover{\n"
                                       "    background-color:rgba(255, 107, 107, 255);\n"
                                       "}")

        self.loginWindow.setObjectName("loginWindow")
        self.label = QtWidgets.QLabel(parent=self.loginWindow)
        self.label.setGeometry(QtCore.QRect(390, 43, 431, 461))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
                                 "border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.loginWindow)
        self.label_2.setGeometry(QtCore.QRect(-1, 25, 411, 501))
        self.label_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255, 107, 107, 255));\n"
            "border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.loginWindow)
        self.label_3.setGeometry(QtCore.QRect(440, 100, 231, 41))
        font = QtGui.QFont()
        font.setFamily("MS shell dlg 2")
        font.setPointSize(21)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);\n"
                                   "font-family: MS shell dlg 2;")
        self.label_3.setObjectName("label_3")
        self.Userlbl = QtWidgets.QLineEdit(parent=self.loginWindow)
        self.Userlbl.setGeometry(QtCore.QRect(440, 170, 341, 61))
        font = QtGui.QFont()
        font.setFamily("MS shell dlg 2")
        font.setPointSize(15)
        self.Userlbl.setFont(font)
        self.Userlbl.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                   "border: 2px solid rgba(0,0,0,0);\n"
                                   "border-bottom-color:rgba(46,82,101,200);\n"
                                   "color:rgba(0,0,0);\n"
                                   "padding-bottom: 7px;\n"
                                   "font-family: MS shell dlg 2;")
        self.Userlbl.setObjectName("Userlbl")
        self.loginbtn = QtWidgets.QPushButton(parent=self.loginWindow)
        self.loginbtn.setGeometry(QtCore.QRect(440, 390, 341, 51))
        font = QtGui.QFont()
        font.setFamily("MS shell dlg 2")
        font.setPointSize(17)
        font.setBold(True)
        self.loginbtn.setFont(font)
        self.loginbtn.setAutoFillBackground(False)
        self.loginbtn.setStyleSheet("font-family: MS shell dlg 2;")
        self.loginbtn.setObjectName("loginbtn")
        self.label_4 = QtWidgets.QLabel(parent=self.loginWindow)
        self.label_4.setGeometry(QtCore.QRect(0, 330, 421, 221))
        font = QtGui.QFont()
        font.setFamily("Mountain")
        font.setPointSize(244)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-family: Mountain;\n"
                                   "color:rgba(255, 107, 107, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.loginWindow)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 471, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("clinicLOGO.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.loginWindow)
        self.label_6.setGeometry(QtCore.QRect(-30, 240, 491, 251))
        self.label_6.setPixmap(QtGui.QPixmap("Untitled design (1).png"))
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.invalidLBL = QtWidgets.QLabel(parent=self.loginWindow)
        self.invalidLBL.setGeometry(QtCore.QRect(540, 460, 151, 31))
        passfont = QtGui.QFont()
        passfont.setPointSize(12)
        passfont.setFamily("MS shell dlg 2")
        passfont.setBold(True)
        self.invalidLBL.setFont(passfont)
        self.invalidLBL.setObjectName("invalidLBL")
        self.Passlbl = QtWidgets.QLineEdit(parent=self.loginWindow)
        self.Passlbl.setGeometry(QtCore.QRect(440, 280, 341, 61))
        font = QtGui.QFont()
        font.setFamily("MS shell dlg 2")
        font.setPointSize(15)
        self.Passlbl.setFont(font)
        self.Passlbl.setStyleSheet("background-color:rgba(0,0,0,0);\n"
                                   "border: 2px solid rgba(0,0,0,0);\n"
                                   "border-bottom-color:rgba(46,82,101,200);\n"
                                   "color:rgba(0,0,0);\n"
                                   "padding-bottom: 7px;\n"
                                   "font-family: MS shell dlg 2;")
        self.Passlbl.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Passlbl.setObjectName("Passlbl")

        lblshadow = QtWidgets.QGraphicsDropShadowEffect()
        lblshadow2 = QtWidgets.QGraphicsDropShadowEffect()
        btnshadow = QtWidgets.QGraphicsDropShadowEffect()
        lblshadow.setBlurRadius(25)
        lblshadow.setXOffset(0)
        lblshadow.setYOffset(0)
        lblshadow2.setBlurRadius(25)
        lblshadow2.setXOffset(0)
        lblshadow2.setYOffset(0)

        btnshadow.setBlurRadius(25)
        btnshadow.setXOffset(3)
        btnshadow.setYOffset(3)

        self.label.setGraphicsEffect(lblshadow)
        self.label_2.setGraphicsEffect(lblshadow2)
        self.loginbtn.setGraphicsEffect(btnshadow)

        self.Xbtn = QtWidgets.QPushButton(parent=self.loginWindow)
        self.Xbtn.setGeometry(QtCore.QRect(785, 50, 31, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.Xbtn.setFont(font)
        self.Xbtn.setObjectName("Xbtn")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label_3.setText(_translate("LoginForm", "Log in as Admin"))
        self.Userlbl.setPlaceholderText(_translate("LoginForm", "Username"))
        self.loginbtn.setText(_translate("LoginForm", "L o g  I n"))
        self.label_4.setText(_translate("LoginForm", "-\'"))
        self.Passlbl.setPlaceholderText(_translate("LoginForm", "Password"))
        self.Xbtn.setText(_translate("LoginForm", "X"))
